### ISSUE TITLE
RRS as default Storage Class?

### ISSUE THREAD

**Issue by haimizrael** [ind9/gocd-s3-artifacts#23]
We started using the ind9 s3 plugins a few months ago, and were unpleasantly surprised change #14 came in the 1.0.29 patch release. 
We do not want to use RSS, and have 3 issues with this change:

1. There is no option to turn this off and use Standard redundancy (unless one forks the code)

1. It is a breaking change, not a bug-fix, so including it in a patch release could cause users of the plugin to miss the fact their artifacts suddenly start getting stored in lower redundancy

1. It could have been made backward compatible for existing users of the plugin (leave the Standard storage class by default, and set an alternate storage class with a parameter - environment variable - wherever the s3.publish plugin)

We have a fork (GCM Grosvenor), where we've added 2 features: (optional) ability to encrypt uploaded artifacts with KMS, and (optional) ability to zip archive contents prior to upload to reduce latency in case of many files being uploaded), as well as fixing a couple of bugs.  The presence of this change #14 prevents us from issuing a pull request and contributing to the common code, without making our own breaking change to this feature.  

Please consider the 3 points above and advise whether you'd be open to making this feature somehow backward compatible.

**Comment by manojlds** [comment]
@haimizrael - apologies. We have not really been great at releases here, and thanks for bringing this up and keeping us honest.

We will definitely make a change to make RRS as an option, and probably move the plugin to a 2.0.0 release as well. We would love to get the features you mention in your fork.

Thanks for taking the time!

**Comment by haimizrael** [comment]
Sounds good: I'll send as a PR (first sending a PR for the other issue (#24).

Glad to be contributing to this project.
