### ISSUE TITLE
Turning on IAM Role credentials cannot be disabled

### ISSUE THREAD

**Issue by haimizrael** [ind9/gocd-s3-artifacts#24]
The recently added item #21 is a nice addition to the AWS credentials options (at GCM we had implemented our own version of that but reverted back to the #21 implementation when we noticed the pull request).  One issue, however, is that because turning on this functionality it is based simply on the existence of the environment variable, there is no way to enable the feature at a higher level (e.g. Go Environment level) but be able to turn it off at a lower level (e.g. pipeline or stage).  Would you consider instead checking for a particular value (e.g. [Tt]rue, [Yy]es, 1 vs. False/No/0)?

**Comment by manojlds** [comment]
@haimizrael - definitely, useful to have this. Will you be able to send a PR based on your implementation?

**Comment by haimizrael** [comment]
Yes, for sure: will send PR likely on Monday.

Thanks!

**Comment by haimizrael** [comment]
Closing this due to merged PR
