### ISSUE TITLE
Fetch S3 artifact task is returning Error: null

### ISSUE THREAD

**Issue by bsnchan** [ind9/gocd-s3-artifacts#5]
We recently built the s3 plugins using the `./build.sh` script.

However when attempting to fetch artifacts from a s3 package, we get the following error:
```
[go] Start to execute task: Plugin with ID: indix.s3fetch. 
Error: null
```

This is the set up we have:
* pipeline-a publishes an artifact to s3
* pipeline-b has a s3 bucket as the material: `Repository: [s3_bucket=my-artifacts] - Package: [pipeline_name=pipeline-a, stage_name=<my-stage>, job_name=<my-job>]`. This has the material name "S3Bucket:my-package"
* pipeline-b has a task to Fetch s3 package with the properties `Repo: S3Bucket Package: my-package Destination: artifacts`

We are not sure if this is the plugin itself. We tried to add debug statements to print to the console when inside the [ExecutionResult method](https://github.com/ind9/gocd-s3-artifacts/blob/master/fetch/src/main/java/com/indix/gocd/s3fetch/FetchExecutor.java#L23) but nothing seems to be printed out. 

Please let us know if you think this may be due to the plugin being built incorrectly.

**Comment by sriram-r** [comment]
I'm assuming the S3 Material plugin is setup on the same Go server. Can you dig up the go-server logs to see if there are some errors there? If you can ```pastebin``` the logs, it would be useful

**Comment by bsnchan** [comment]
@sriram-r 

The paste bin link can be found [here](http://pastebin.com/W4hTb180). Thanks for all your help!

**Comment by sriram-r** [comment]
I couldn't glean much from the logs either. Here's what I would suggest.
- Please verify if the S3 material plugin is setup and picked up by the Go Server
- Please check if there's anything in the Go server log for this material. Are Material updates for this material going through fine?
- Does the agent get the revision number when it tries to fetch a package...

Finally, might be silly, I hope the AWS S3 credentials are correct.

**Comment by bsnchan** [comment]
An interesting thing I found from the server logs is that the material plugin is able to detect a modification in my s3 bucket successfully. However, the directory that the logs say is the flyweight's working directory does not actually exist on the Go Server. 

If you look at the [logs](http://pastebin.com/Lg3eiGk8), on line 14 it says the flyweight's working directory is `/var/vcap/store/gocd/pipelines/flyweight/cd318fd5-43ab-4830-baa0-d14fbeff43a9` but the directory does not actually exist.

**Comment by manojlds** [comment]
Hi @bsnchan 

To help us debug the issue, can you please give some details on your setup, especially on how you have configured the AWS credentials?

Also, can you provide the full job log (to see the environment variables set by the Materials plugin.)

Thanks
Manoj

**Comment by manojlds** [comment]
@bsnchan Can you also please try the latest build from here - https://github.com/ind9/gocd-s3-artifacts/releases/tag/v1.0.21

Thanks
Manoj

**Comment by bsnchan** [comment]
Hi @manojlds 

We tried the latest build for our pipelines. The logs still kind of look the same - the flyweight working directory in the log does not actually exist on the Go Server. You can find the logs [here](http://pastebin.com/GZ0NTRFc).

The job log can be found [here](http://pastebin.com/ZDtskwEw).

Again, thank you so much for all your help. We really appreciate it!

Thanks,
Brenda and Derwei

**Comment by ashwanthkumar** [comment]
@bsnchan Can you check / share the agent logs? You can find them on `/var/vcap/data/gocd-agent/go-agent.log`. We're looking for some ERROR messages or java stack traces in there when the task is executed.

**Comment by bsnchan** [comment]
@ashwanthkumar 

I have attached the go-agent logs [here](http://pastebin.com/6dsULHx5). There is one runtime exception.

**Comment by ashwanthkumar** [comment]
And, nothing on the `plugin-indix.s3fetch.log` ?

**Comment by bsnchan** [comment]
There are no files called `plugin-indix.s3fetch.log` on our go-agent. We did a `find` on the whole system to search for it.

**Comment by manojlds** [comment]
I was able to reproduce the issue if I configure the `Fetch` task wrongly i.e give wrong Repo name or Package name. Can you please check the configuration, and also post a screenshot from the admin screen? From your job log, your repo name must be `S3_ARTIFACTS` and package name must be `PUBLISH_S3_ARTIFACT`

The plugin is not informing configuration issues well, so we will also make changes to ensure that we get better error messages in such cases.

**Comment by bsnchan** [comment]
@manojlds Thanks for all your help!

It looks like the fetch plugin converts all dashes to underscores. Our repo and package names were "s3-artifacts" and "publish-s3-artifact" in both the Admin screen and Materials screen. The fetch plugin required theses to be "s3_artifacts" and "publish_s3_artifact" to work correctly.

**Comment by manojlds** [comment]
@bsnchan - Glad it works! Please do take the latest [build](https://github.com/ind9/gocd-s3-artifacts/releases/tag/v1.0.22) as that has better validation and error messages.

Actually, Go changes the names to have underscores when it creates the environment variables . I will track this in a separate issue to see if the plugin can handle this better.

Please do provide us with feedback on your usage of these plugins!
